# Basic Information 
title: Sota Minowa
position: PhD Student in Social Science
affiliation: Caltech
email: sota.minowa@caltech.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: sota minowa, minowa Sota, sotaminowa
description: 
canonical: https://sota.minowa.github.io

# Links 
# If you don't need one of them, you may delete the corresponding line.
# google_scholar: https://scholar.google.com/
cv_link: assets/files/academic_cv.pdf
# github_link: https://github.com/
# linkedin: https://www.linkedin.com/
# twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar2.jpg
favicon: ./assets/img/favicon-75.png
# favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
# NEED THIS
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"
# font: "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: UA-111540567-4

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
